### ISSUE TITLE
German: All 14 volumes of the 'Große Ausgabe' (1.–7. Auflage, 1812–1857) Kinder- und Hausmärchen

### ISSUE THREAD

**Issue by cthomasdta** [Digital-Folkloristics/Digital-Breadcrumbs-of-Brothers-Grimm#22]
you might be interested to hear that in the German Text Archive (http://www.deutschestextarchiv.de/) we recently integrated *all* contemporary editions of Grimms Maerchen, cf. http://www.deutschestextarchiv.de/api/pnd/118542265.
cf. http://www.deutschestextarchiv.de/news/66

**Comment by gfranzini** [comment]
Thank you, this is indeed very interesting! I forwarded it to my colleagues. 👍
